name: sample_admin_panel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.4
  geolocator: ^13.0.1
  google_maps_flutter: ^2.1.1
  http: ^1.2.2
  intl: ^0.19.0
  mqtt_client: ^10.5.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

